# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-13 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200106_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(max_length=256, verbose_name='个人形象的URL'),
        ),
    ]
