# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-14 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200113_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vip_end',
            field=models.DateTimeField(default='2100-01-01', verbose_name='会员过期时间'),
        ),
        migrations.AddField(
            model_name='user',
            name='vip_id',
            field=models.IntegerField(default=1, verbose_name='用户对应的会员ID'),
        ),
    ]
